# `=== Atelier Pandas ===`

### `Partie 1 - Series`

#### `1.1 Création d'une Series contenant 4 températures`

In [2]:
import pandas as pd

# Creation de la serie a partir d'une list
temperatures = [25, 34, 23, 40]
serie = pd.Series(temperatures)
serie

0    25
1    34
2    23
3    40
dtype: int64

#### `1.2 Affichage de l'index`

In [7]:
serie.index

RangeIndex(start=0, stop=4, step=1)

#### `1.3 Affichage de la 1ère valeur`

In [8]:
serie[0]

np.int64(25)

#### `1.4 Affichage de la dernière valeur`

In [11]:
serie.iloc[-1]

np.int64(40)

#### `1.5 Création, de deux façon différentes, d'une Series de 4 températures avec comme index les heures demesure 12h, 13h, 14h et 15h`

In [ ]:
# Methode 1: a partir d'un dictionnaire
dict_temp = {
     "12h": 34,
     "13h": 23,
     "14h": 40,
     "15h": 37
}
serie_1 = pd.Series(dict_temp)
serie_1

12h    34
13h    23
14h    40
15h    37
dtype: int64

In [13]:
# Methode 2: A partir d'une liste,
indexes = ["12h", "13h", "14h", "15h"] 
serie_2 = pd.Series(temperatures, index=indexes)
serie_2

12h    25
13h    34
14h    23
15h    40
dtype: int64

#### `1.6 Affichage de la 1ère et la dernière valeur`

In [15]:
#
serie_2.iloc[[0, -1]]

12h    25
15h    40
dtype: int64

### `=== Partie 2 – DataFrame ===`

#### `2.1 Création et affichage du dataframe df_test à partir du dictionnaire suivant`


data = {
"capteur": ["C001", "C002", "C003"],
"temperature": [24.5, 25.1, 26.3],
"humidite": [65, 67, 70]

In [16]:
data = {
     "capteur": ["C001", "C002", "C003"],
     "temperature": [24.5, 25.1, 26.3],
     "humidite": [65, 67, 70]
}

df_test = pd.DataFrame(data)
df_test

  capteur  temperature  humidite
0    C001         24.5        65
1    C002         25.1        67
2    C003         26.3        70

#### `2.2 Importation du dataset mesures_capteurs.csv dans le dataframe df`

In [20]:
df = pd.read_csv("../data/mesures_capteurs.csv")
df

,id_mesure,date_heure,id_capteur,batiment,temperature,humidite,pression,consommation,etat
0,M0413,2026-01-22 04:00:00,C005,B002,25.46,58.06,1008.95,287.28,OK
1,M0290,2026-01-17 01:00:00,C002,B001,24.00,79.73,993.39,116.20,OK
2,M0077,2026-01-08 04:00:00,C005,B002,25.82,54.47,1010.32,288.50,OK
3,M0079,2026-01-08 06:00:00,C007,B003,28.23,69.39,1019.62,136.65,OK
4,M0183,2026-01-12 14:00:00,C003,B001,20.58,53.80,1016.58,182.62,OK
...,...,...,...,...,...,...,...,...,...
600,M0072,2026-01-07 23:00:00,C012,B004,23.67,60.28,1015.11,282.36,OK
601,M0107,2026-01-09 10:00:00,C011,B004,24.34,61.42,1019.43,357.43,OK
602,M0271,2026-01-16 06:00:00,C007,B003,23.73,63.49,1016.46,152.79,OK
603,M0436,2026-01-23 03:00:00,C004,B002,24.83,79.77,1017.05,170.97,OK
604,M0103,2026-01-09 06:00:00,C007,B003,17.02,52.04,1001.14,44.99,OK

#### `2.3 Affichage des dimensions de df`

In [23]:
print(f"Dimensions du dataset: {df.shape}")

Dimensions du dataset: (605, 9)